## 4.1. Numpy ndarray: 다차원 배열 객체

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2,3)

In [3]:
data

array([[ 7.20908342e-04,  1.81660055e+00, -4.27221520e-01],
       [-5.10156757e-01, -8.92195474e-01,  7.84347975e-01]])

In [4]:
data * 10 

array([[ 7.20908342e-03,  1.81660055e+01, -4.27221520e+00],
       [-5.10156757e+00, -8.92195474e+00,  7.84347975e+00]])

In [5]:
data + data 

array([[ 1.44181668e-03,  3.63320109e+00, -8.54443041e-01],
       [-1.02031351e+00, -1.78439095e+00,  1.56869595e+00]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

## 4.1.1 ndarray 생성

In [8]:
data1 = [6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)

In [10]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [13]:
arr2 = np.array(data2)

In [14]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 4)

In [17]:
arr1.dtype

dtype('float64')

In [19]:
arr2.dtype

dtype('int64')

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2,3,2))

array([[[2.56659277e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 4.1.2 ndarray 의 지료형

In [ ]:
arr1